openapi: 3.0.0
info:
  title: Route schema
  description: Route schema
  version: 1.0.0
paths: {}
components:
  schemas:
    IRoute:
      type: object
      properties:
        href:
          description: Route href
          type: string
        label:
          description: Route label
          type: string
      required:
        - href
        - label
    IExtendedRoute:
      allOf: # Combines the HuiRoute and the inline model
        - $ref: '#/components/schemas/IRoute'
        - type: object
          properties:
            timestamp:
              type: integer
          required:
            - timestamp
